/**
 *
 *  PayIdempotency.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "PayIdempotency.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::pay_test;

const std::string PayIdempotency::Cols::_idempotency_key = "\"idempotency_key\"";
const std::string PayIdempotency::Cols::_request_hash = "\"request_hash\"";
const std::string PayIdempotency::Cols::_response_snapshot = "\"response_snapshot\"";
const std::string PayIdempotency::Cols::_expire_at = "\"expire_at\"";
const std::string PayIdempotency::Cols::_created_at = "\"created_at\"";
const std::string PayIdempotency::Cols::_updated_at = "\"updated_at\"";
const std::string PayIdempotency::Cols::_owner_token = "\"owner_token\"";
const std::string PayIdempotency::primaryKeyName = "idempotency_key";
const bool PayIdempotency::hasPrimaryKey = true;
const std::string PayIdempotency::tableName = "\"pay_idempotency\"";

const std::vector<typename PayIdempotency::MetaData> PayIdempotency::metaData_={
{"idempotency_key","std::string","character varying",128,0,1,1},
{"request_hash","std::string","character varying",64,0,0,1},
{"response_snapshot","std::string","text",0,0,0,0},
{"expire_at","::trantor::Date","timestamp without time zone",0,0,0,0},
{"created_at","::trantor::Date","timestamp without time zone",0,0,0,1},
{"updated_at","::trantor::Date","timestamp without time zone",0,0,0,1},
{"owner_token","std::string","character varying",64,0,0,0}
};
const std::string &PayIdempotency::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
PayIdempotency::PayIdempotency(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["idempotency_key"].isNull())
        {
            idempotencyKey_=std::make_shared<std::string>(r["idempotency_key"].as<std::string>());
        }
        if(!r["request_hash"].isNull())
        {
            requestHash_=std::make_shared<std::string>(r["request_hash"].as<std::string>());
        }
        if(!r["response_snapshot"].isNull())
        {
            responseSnapshot_=std::make_shared<std::string>(r["response_snapshot"].as<std::string>());
        }
        if(!r["expire_at"].isNull())
        {
            auto timeStr = r["expire_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                expireAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["created_at"].isNull())
        {
            auto timeStr = r["created_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["updated_at"].isNull())
        {
            auto timeStr = r["updated_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["owner_token"].isNull())
        {
            ownerToken_=std::make_shared<std::string>(r["owner_token"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 7 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            idempotencyKey_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            requestHash_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            responseSnapshot_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                expireAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            ownerToken_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

PayIdempotency::PayIdempotency(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 7)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            idempotencyKey_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            requestHash_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            responseSnapshot_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[3]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                expireAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[4]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[5]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            ownerToken_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
}

PayIdempotency::PayIdempotency(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("idempotency_key"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["idempotency_key"].isNull())
        {
            idempotencyKey_=std::make_shared<std::string>(pJson["idempotency_key"].asString());
        }
    }
    if(pJson.isMember("request_hash"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["request_hash"].isNull())
        {
            requestHash_=std::make_shared<std::string>(pJson["request_hash"].asString());
        }
    }
    if(pJson.isMember("response_snapshot"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["response_snapshot"].isNull())
        {
            responseSnapshot_=std::make_shared<std::string>(pJson["response_snapshot"].asString());
        }
    }
    if(pJson.isMember("expire_at"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["expire_at"].isNull())
        {
            auto timeStr = pJson["expire_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                expireAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["created_at"].isNull())
        {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("updated_at"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["updated_at"].isNull())
        {
            auto timeStr = pJson["updated_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("owner_token"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["owner_token"].isNull())
        {
            ownerToken_=std::make_shared<std::string>(pJson["owner_token"].asString());
        }
    }
}

void PayIdempotency::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 7)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            idempotencyKey_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            requestHash_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            responseSnapshot_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[3]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                expireAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[4]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[5]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            ownerToken_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
}

void PayIdempotency::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("idempotency_key"))
    {
        if(!pJson["idempotency_key"].isNull())
        {
            idempotencyKey_=std::make_shared<std::string>(pJson["idempotency_key"].asString());
        }
    }
    if(pJson.isMember("request_hash"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["request_hash"].isNull())
        {
            requestHash_=std::make_shared<std::string>(pJson["request_hash"].asString());
        }
    }
    if(pJson.isMember("response_snapshot"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["response_snapshot"].isNull())
        {
            responseSnapshot_=std::make_shared<std::string>(pJson["response_snapshot"].asString());
        }
    }
    if(pJson.isMember("expire_at"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["expire_at"].isNull())
        {
            auto timeStr = pJson["expire_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                expireAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["created_at"].isNull())
        {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("updated_at"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["updated_at"].isNull())
        {
            auto timeStr = pJson["updated_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("owner_token"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["owner_token"].isNull())
        {
            ownerToken_=std::make_shared<std::string>(pJson["owner_token"].asString());
        }
    }
}

const std::string &PayIdempotency::getValueOfIdempotencyKey() const noexcept
{
    static const std::string defaultValue = std::string();
    if(idempotencyKey_)
        return *idempotencyKey_;
    return defaultValue;
}
const std::shared_ptr<std::string> &PayIdempotency::getIdempotencyKey() const noexcept
{
    return idempotencyKey_;
}
void PayIdempotency::setIdempotencyKey(const std::string &pIdempotencyKey) noexcept
{
    idempotencyKey_ = std::make_shared<std::string>(pIdempotencyKey);
    dirtyFlag_[0] = true;
}
void PayIdempotency::setIdempotencyKey(std::string &&pIdempotencyKey) noexcept
{
    idempotencyKey_ = std::make_shared<std::string>(std::move(pIdempotencyKey));
    dirtyFlag_[0] = true;
}
const typename PayIdempotency::PrimaryKeyType & PayIdempotency::getPrimaryKey() const
{
    assert(idempotencyKey_);
    return *idempotencyKey_;
}

const std::string &PayIdempotency::getValueOfRequestHash() const noexcept
{
    static const std::string defaultValue = std::string();
    if(requestHash_)
        return *requestHash_;
    return defaultValue;
}
const std::shared_ptr<std::string> &PayIdempotency::getRequestHash() const noexcept
{
    return requestHash_;
}
void PayIdempotency::setRequestHash(const std::string &pRequestHash) noexcept
{
    requestHash_ = std::make_shared<std::string>(pRequestHash);
    dirtyFlag_[1] = true;
}
void PayIdempotency::setRequestHash(std::string &&pRequestHash) noexcept
{
    requestHash_ = std::make_shared<std::string>(std::move(pRequestHash));
    dirtyFlag_[1] = true;
}

const std::string &PayIdempotency::getValueOfResponseSnapshot() const noexcept
{
    static const std::string defaultValue = std::string();
    if(responseSnapshot_)
        return *responseSnapshot_;
    return defaultValue;
}
const std::shared_ptr<std::string> &PayIdempotency::getResponseSnapshot() const noexcept
{
    return responseSnapshot_;
}
void PayIdempotency::setResponseSnapshot(const std::string &pResponseSnapshot) noexcept
{
    responseSnapshot_ = std::make_shared<std::string>(pResponseSnapshot);
    dirtyFlag_[2] = true;
}
void PayIdempotency::setResponseSnapshot(std::string &&pResponseSnapshot) noexcept
{
    responseSnapshot_ = std::make_shared<std::string>(std::move(pResponseSnapshot));
    dirtyFlag_[2] = true;
}
void PayIdempotency::setResponseSnapshotToNull() noexcept
{
    responseSnapshot_.reset();
    dirtyFlag_[2] = true;
}

const ::trantor::Date &PayIdempotency::getValueOfExpireAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(expireAt_)
        return *expireAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &PayIdempotency::getExpireAt() const noexcept
{
    return expireAt_;
}
void PayIdempotency::setExpireAt(const ::trantor::Date &pExpireAt) noexcept
{
    expireAt_ = std::make_shared<::trantor::Date>(pExpireAt);
    dirtyFlag_[3] = true;
}
void PayIdempotency::setExpireAtToNull() noexcept
{
    expireAt_.reset();
    dirtyFlag_[3] = true;
}

const ::trantor::Date &PayIdempotency::getValueOfCreatedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(createdAt_)
        return *createdAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &PayIdempotency::getCreatedAt() const noexcept
{
    return createdAt_;
}
void PayIdempotency::setCreatedAt(const ::trantor::Date &pCreatedAt) noexcept
{
    createdAt_ = std::make_shared<::trantor::Date>(pCreatedAt);
    dirtyFlag_[4] = true;
}

const ::trantor::Date &PayIdempotency::getValueOfUpdatedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(updatedAt_)
        return *updatedAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &PayIdempotency::getUpdatedAt() const noexcept
{
    return updatedAt_;
}
void PayIdempotency::setUpdatedAt(const ::trantor::Date &pUpdatedAt) noexcept
{
    updatedAt_ = std::make_shared<::trantor::Date>(pUpdatedAt);
    dirtyFlag_[5] = true;
}

const std::string &PayIdempotency::getValueOfOwnerToken() const noexcept
{
    static const std::string defaultValue = std::string();
    if(ownerToken_)
        return *ownerToken_;
    return defaultValue;
}
const std::shared_ptr<std::string> &PayIdempotency::getOwnerToken() const noexcept
{
    return ownerToken_;
}
void PayIdempotency::setOwnerToken(const std::string &pOwnerToken) noexcept
{
    ownerToken_ = std::make_shared<std::string>(pOwnerToken);
    dirtyFlag_[6] = true;
}
void PayIdempotency::setOwnerToken(std::string &&pOwnerToken) noexcept
{
    ownerToken_ = std::make_shared<std::string>(std::move(pOwnerToken));
    dirtyFlag_[6] = true;
}
void PayIdempotency::setOwnerTokenToNull() noexcept
{
    ownerToken_.reset();
    dirtyFlag_[6] = true;
}

void PayIdempotency::updateId(const uint64_t id)
{
}

const std::vector<std::string> &PayIdempotency::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "idempotency_key",
        "request_hash",
        "response_snapshot",
        "expire_at",
        "created_at",
        "updated_at",
        "owner_token"
    };
    return inCols;
}

void PayIdempotency::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getIdempotencyKey())
        {
            binder << getValueOfIdempotencyKey();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getRequestHash())
        {
            binder << getValueOfRequestHash();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getResponseSnapshot())
        {
            binder << getValueOfResponseSnapshot();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getExpireAt())
        {
            binder << getValueOfExpireAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getUpdatedAt())
        {
            binder << getValueOfUpdatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getOwnerToken())
        {
            binder << getValueOfOwnerToken();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> PayIdempotency::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    return ret;
}

void PayIdempotency::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getIdempotencyKey())
        {
            binder << getValueOfIdempotencyKey();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getRequestHash())
        {
            binder << getValueOfRequestHash();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getResponseSnapshot())
        {
            binder << getValueOfResponseSnapshot();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getExpireAt())
        {
            binder << getValueOfExpireAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getUpdatedAt())
        {
            binder << getValueOfUpdatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getOwnerToken())
        {
            binder << getValueOfOwnerToken();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value PayIdempotency::toJson() const
{
    Json::Value ret;
    if(getIdempotencyKey())
    {
        ret["idempotency_key"]=getValueOfIdempotencyKey();
    }
    else
    {
        ret["idempotency_key"]=Json::Value();
    }
    if(getRequestHash())
    {
        ret["request_hash"]=getValueOfRequestHash();
    }
    else
    {
        ret["request_hash"]=Json::Value();
    }
    if(getResponseSnapshot())
    {
        ret["response_snapshot"]=getValueOfResponseSnapshot();
    }
    else
    {
        ret["response_snapshot"]=Json::Value();
    }
    if(getExpireAt())
    {
        ret["expire_at"]=getExpireAt()->toDbStringLocal();
    }
    else
    {
        ret["expire_at"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    if(getUpdatedAt())
    {
        ret["updated_at"]=getUpdatedAt()->toDbStringLocal();
    }
    else
    {
        ret["updated_at"]=Json::Value();
    }
    if(getOwnerToken())
    {
        ret["owner_token"]=getValueOfOwnerToken();
    }
    else
    {
        ret["owner_token"]=Json::Value();
    }
    return ret;
}

std::string PayIdempotency::toString() const
{
    return toJson().toStyledString();
}

Json::Value PayIdempotency::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 7)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getIdempotencyKey())
            {
                ret[pMasqueradingVector[0]]=getValueOfIdempotencyKey();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getRequestHash())
            {
                ret[pMasqueradingVector[1]]=getValueOfRequestHash();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getResponseSnapshot())
            {
                ret[pMasqueradingVector[2]]=getValueOfResponseSnapshot();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getExpireAt())
            {
                ret[pMasqueradingVector[3]]=getExpireAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getCreatedAt())
            {
                ret[pMasqueradingVector[4]]=getCreatedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getUpdatedAt())
            {
                ret[pMasqueradingVector[5]]=getUpdatedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getOwnerToken())
            {
                ret[pMasqueradingVector[6]]=getValueOfOwnerToken();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getIdempotencyKey())
    {
        ret["idempotency_key"]=getValueOfIdempotencyKey();
    }
    else
    {
        ret["idempotency_key"]=Json::Value();
    }
    if(getRequestHash())
    {
        ret["request_hash"]=getValueOfRequestHash();
    }
    else
    {
        ret["request_hash"]=Json::Value();
    }
    if(getResponseSnapshot())
    {
        ret["response_snapshot"]=getValueOfResponseSnapshot();
    }
    else
    {
        ret["response_snapshot"]=Json::Value();
    }
    if(getExpireAt())
    {
        ret["expire_at"]=getExpireAt()->toDbStringLocal();
    }
    else
    {
        ret["expire_at"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    if(getUpdatedAt())
    {
        ret["updated_at"]=getUpdatedAt()->toDbStringLocal();
    }
    else
    {
        ret["updated_at"]=Json::Value();
    }
    if(getOwnerToken())
    {
        ret["owner_token"]=getValueOfOwnerToken();
    }
    else
    {
        ret["owner_token"]=Json::Value();
    }
    return ret;
}

bool PayIdempotency::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("idempotency_key"))
    {
        if(!validJsonOfField(0, "idempotency_key", pJson["idempotency_key"], err, true))
            return false;
    }
    else
    {
        err="The idempotency_key column cannot be null";
        return false;
    }
    if(pJson.isMember("request_hash"))
    {
        if(!validJsonOfField(1, "request_hash", pJson["request_hash"], err, true))
            return false;
    }
    else
    {
        err="The request_hash column cannot be null";
        return false;
    }
    if(pJson.isMember("response_snapshot"))
    {
        if(!validJsonOfField(2, "response_snapshot", pJson["response_snapshot"], err, true))
            return false;
    }
    if(pJson.isMember("expire_at"))
    {
        if(!validJsonOfField(3, "expire_at", pJson["expire_at"], err, true))
            return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(4, "created_at", pJson["created_at"], err, true))
            return false;
    }
    if(pJson.isMember("updated_at"))
    {
        if(!validJsonOfField(5, "updated_at", pJson["updated_at"], err, true))
            return false;
    }
    if(pJson.isMember("owner_token"))
    {
        if(!validJsonOfField(6, "owner_token", pJson["owner_token"], err, true))
            return false;
    }
    return true;
}
bool PayIdempotency::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                        const std::vector<std::string> &pMasqueradingVector,
                                                        std::string &err)
{
    if(pMasqueradingVector.size() != 7)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[0] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool PayIdempotency::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("idempotency_key"))
    {
        if(!validJsonOfField(0, "idempotency_key", pJson["idempotency_key"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("request_hash"))
    {
        if(!validJsonOfField(1, "request_hash", pJson["request_hash"], err, false))
            return false;
    }
    if(pJson.isMember("response_snapshot"))
    {
        if(!validJsonOfField(2, "response_snapshot", pJson["response_snapshot"], err, false))
            return false;
    }
    if(pJson.isMember("expire_at"))
    {
        if(!validJsonOfField(3, "expire_at", pJson["expire_at"], err, false))
            return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(4, "created_at", pJson["created_at"], err, false))
            return false;
    }
    if(pJson.isMember("updated_at"))
    {
        if(!validJsonOfField(5, "updated_at", pJson["updated_at"], err, false))
            return false;
    }
    if(pJson.isMember("owner_token"))
    {
        if(!validJsonOfField(6, "owner_token", pJson["owner_token"], err, false))
            return false;
    }
    return true;
}
bool PayIdempotency::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                      const std::vector<std::string> &pMasqueradingVector,
                                                      std::string &err)
{
    if(pMasqueradingVector.size() != 7)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool PayIdempotency::validJsonOfField(size_t index,
                                      const std::string &fieldName,
                                      const Json::Value &pJson,
                                      std::string &err,
                                      bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 128)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 128)";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 64)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 64)";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 64)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 64)";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
