#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Docs/AI-config drift guard (CI gate + local check).

The authforge benchmark showed that hand-maintained agent inventories and
spec docs rot within weeks. This gate makes the three historically-broken
invariants fail loudly:

  R1  AGENTS.md "Claude Code Assets" lists exactly what exists on disk
      under .claude/{agents,rules,skills}/ (tombstones must be listed,
      annotated with [retired]).
  R2  Repo paths written in backticks in the governance docs must exist
      (a doc may not point at a file that isn't there; forward refs to
      files a later governance phase delivers need an explicit entry in
      PENDING_PATHS below).
  R3  No gtest vocabulary outside docs/history/ and CHANGELOG.md — the
      suite is Drogon DROGON_TEST; gtest examples in agent docs were
      actively misleading (see 2026-09 drift audit).

Exit code 0 = all rules pass; 1 = violations (printed one per line).
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
AGENTS_MD = REPO_ROOT / "AGENTS.md"

# ---------------------------------------------------------------- R1

ASSET_SECTIONS = {
    # section header -> (dir under .claude, entry shape)
    "### Agents": (REPO_ROOT / ".claude" / "agents", "file"),
    "### Rules": (REPO_ROOT / ".claude" / "rules", "file"),
    "### Skills": (REPO_ROOT / ".claude" / "skills", "dir"),
}
ASSET_LINE_RE = re.compile(r"^- ([A-Za-z0-9._-]+) \(file: (.+?)\)", re.M)


def check_asset_inventory() -> list[str]:
    errors: list[str] = []
    text = AGENTS_MD.read_text(encoding="utf-8")
    idx = text.find("## Claude Code Assets")
    if idx < 0:
        return ["[rule1 inventory] AGENTS.md has no 'Claude Code Assets' section"]
    inventory = text[idx:]
    for header, (root, shape) in ASSET_SECTIONS.items():
        start = inventory.find(header)
        if start < 0:
            errors.append(f"[rule1 inventory] AGENTS.md missing section '{header}'")
            continue
        end = inventory.find("###", start + len(header))
        body = inventory[start:end if end > 0 else None]
        listed = {}
        for m in ASSET_LINE_RE.finditer(body):
            listed[m.group(1)] = m.group(2)
        if shape == "file":
            actual = {p.stem: f"{root.name}/{p.name}" for p in root.glob("*.md")}
        else:
            actual = {
                p.parent.name: f"{root.name}/{p.parent.name}/SKILL.md"
                for p in root.glob("*/SKILL.md")
            }
        for missing in sorted(set(actual) - set(listed)):
            errors.append(
                f"[rule1 inventory] {header}: on disk but not listed in "
                f"AGENTS.md: {missing} (file: .claude/{actual[missing]})"
            )
        for ghost in sorted(set(listed) - set(actual)):
            errors.append(
                f"[rule1 inventory] {header}: listed in AGENTS.md but not on "
                f"disk: {ghost} (file: .claude/{listed[ghost]})"
            )
    return errors


# ---------------------------------------------------------------- R2

R2_DOCS = [
    REPO_ROOT / "AGENTS.md",
    REPO_ROOT / "CLAUDE.md",
    REPO_ROOT / "TECH_SPECS.md",
    REPO_ROOT / "CONTRIBUTING.md",
] + sorted((REPO_ROOT / "docs").rglob("*.md"))

R2_SKIP_DIRS = ("docs/history/", "docs/superpowers/")  # frozen archives + agent scratch

BACKTICK_RE = re.compile(r"`([^`\n]+)`")
PATHISH_RE = re.compile(
    r"^(?:\.claude|\.codex|\.github|libs|examples|tests|scripts|sql|cmake|docs|"
    r"build|CMakeLists\.txt|conanfile\.py|conan\.lock|"
    r"TECH_SPECS\.md|CHANGELOG\.md|README\.md)(?:[/\\]|$)"
)
PLACEHOLDER_RE = re.compile(
    r"<|>|\*|\{|N{2,}|xxx|XXX|YYYY|NNN|00N|\.\.\.|…|\$|:\d|\s"
)
# Runtime-provisioned secret locations (generated by operators, never tracked).
SECRET_EXTS = (".pem", ".key", ".crt", ".p12", ".pfx")

# Forward references: governance-phase deliverables that docs may cite
# before they land. Each entry needs a reason; prune as phases complete.
PENDING_PATHS = {
    "scripts/measure_coverage.py": "delivered by coverage phase",
    "scripts/coverage_baseline.json": "delivered by coverage phase",
}


def check_doc_paths() -> list[str]:
    errors: list[str] = []
    for doc in R2_DOCS:
        if not doc.is_file():
            continue
        rel_doc = doc.relative_to(REPO_ROOT).as_posix()
        if any(rel_doc.startswith(p) for p in R2_SKIP_DIRS):
            continue
        for lineno, line in enumerate(
            doc.read_text(encoding="utf-8", errors="replace").splitlines(), 1
        ):
            for token in BACKTICK_RE.findall(line):
                token = token.strip()
                if not PATHISH_RE.match(token) or PLACEHOLDER_RE.search(token):
                    continue
                token = token.rstrip(":").strip("/")
                probe = token.replace("\\", "/")
                if probe in PENDING_PATHS:
                    continue
                if probe.endswith(SECRET_EXTS):
                    continue
                if not (REPO_ROOT / probe).exists():
                    errors.append(
                        f"[rule2 dead-path] {rel_doc}:{lineno}: `{token}` does "
                        f"not exist (add to PENDING_PATHS with a reason if "
                        f"this is a deliberate forward reference)"
                    )
    return errors


# ---------------------------------------------------------------- R3

R3_BANNED = (
    "Google Test",
    "google test",
    "TEST_F(",
    "EXPECT_EQ(",
    "EXPECT_TRUE",
    "ASSERT_EQ",
    "gtest_filter",
    "gtest_verbose",
    "--gtest",
    "#include <gtest",
)
R3_ALLOW_LINE_RE = re.compile(r"not gtest|非 gtest|没有 gtest|gtest 宏不存在")
R3_ROOTS = [REPO_ROOT / "AGENTS.md", REPO_ROOT / "CLAUDE.md",
            REPO_ROOT / "TECH_SPECS.md", REPO_ROOT / "CONTRIBUTING.md"]
R3_DIRS = [REPO_ROOT / "docs", REPO_ROOT / ".claude", REPO_ROOT / ".codex"]
R3_SKIP_DIRS = ("docs/history/",)  # archives + CHANGELOG.md keep historical truth


def check_gtest_vocabulary() -> list[str]:
    errors: list[str] = []
    files: list[Path] = list(R3_ROOTS)
    for root in R3_DIRS:
        if not root.is_dir():
            continue
        files += [p for p in root.rglob("*")
                  if p.is_file() and p.suffix in {".md", ".toml", ".py", ".sh"}]
    for f in files:
        rel = f.relative_to(REPO_ROOT).as_posix()
        if any(rel.startswith(p) for p in R3_SKIP_DIRS):
            continue
        for lineno, line in enumerate(
            f.read_text(encoding="utf-8", errors="replace").splitlines(), 1
        ):
            if R3_ALLOW_LINE_RE.search(line):
                continue
            for token in R3_BANNED:
                if token in line:
                    errors.append(
                        f"[rule3 gtest-vocab] {rel}:{lineno}: '{token}' — "
                        f"this repo tests with Drogon DROGON_TEST"
                    )
                    break
    return errors


def main() -> int:
    violations = check_asset_inventory() + check_doc_paths() + check_gtest_vocabulary()
    if violations:
        print(f"Docs drift guard FAILED ({len(violations)} violation(s)):")
        for v in violations:
            print("  " + v)
        return 1
    print("Docs drift guard passed (3 rules: inventory, dead-paths, gtest-vocab).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
