#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Docs/AI-config drift guard (CI gate + local check).

The authforge benchmark showed that hand-maintained agent inventories and
spec docs rot within weeks. This gate makes the four historically-broken
invariants fail loudly:

  R1  AGENTS.md "Claude Code Assets" lists exactly what exists on disk
      under .claude/{agents,rules,skills}/ (tombstones must be listed,
      annotated with [retired]).
  R2  Repo paths written in backticks in the governance docs must exist
      (a doc may not point at a file that isn't there; forward refs to
      files a later governance phase delivers need an explicit entry in
      PENDING_PATHS below).
  R3  No gtest vocabulary outside docs/history/ and CHANGELOG.md — the
      suite is Drogon DROGON_TEST; gtest examples in agent docs were
      actively misleading (see 2026-09 drift audit).
  R4  Migration versions cited in docs and skills must exist in sql/.
      Chains move forward; prose that quotes "001-004" after 005 lands is
      a runbook that will be copy-pasted into a deploy.

Exit code 0 = all rules pass; 1 = violations (printed one per line).
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
AGENTS_MD = REPO_ROOT / "AGENTS.md"

# ---------------------------------------------------------------- R1

ASSET_SECTIONS = {
    # section header -> (dir under .claude, entry shape)
    "### Agents": (REPO_ROOT / ".claude" / "agents", "file"),
    "### Rules": (REPO_ROOT / ".claude" / "rules", "file"),
    "### Skills": (REPO_ROOT / ".claude" / "skills", "dir"),
}
ASSET_LINE_RE = re.compile(r"^- ([A-Za-z0-9._-]+) \(file: (.+?)\)", re.M)


def check_asset_inventory() -> list[str]:
    errors: list[str] = []
    text = AGENTS_MD.read_text(encoding="utf-8")
    idx = text.find("## Claude Code Assets")
    if idx < 0:
        return ["[rule1 inventory] AGENTS.md has no 'Claude Code Assets' section"]
    inventory = text[idx:]
    for header, (root, shape) in ASSET_SECTIONS.items():
        start = inventory.find(header)
        if start < 0:
            errors.append(f"[rule1 inventory] AGENTS.md missing section '{header}'")
            continue
        end = inventory.find("###", start + len(header))
        body = inventory[start:end if end > 0 else None]
        listed = {}
        for m in ASSET_LINE_RE.finditer(body):
            listed[m.group(1)] = m.group(2)
        if shape == "file":
            actual = {p.stem: f"{root.name}/{p.name}" for p in root.glob("*.md")}
        else:
            actual = {
                p.parent.name: f"{root.name}/{p.parent.name}/SKILL.md"
                for p in root.glob("*/SKILL.md")
            }
        for missing in sorted(set(actual) - set(listed)):
            errors.append(
                f"[rule1 inventory] {header}: on disk but not listed in "
                f"AGENTS.md: {missing} (file: .claude/{actual[missing]})"
            )
        for ghost in sorted(set(listed) - set(actual)):
            errors.append(
                f"[rule1 inventory] {header}: listed in AGENTS.md but not on "
                f"disk: {ghost} (file: .claude/{listed[ghost]})"
            )
    return errors


# ---------------------------------------------------------------- R2

R2_DOCS = [
    REPO_ROOT / "AGENTS.md",
    REPO_ROOT / "CLAUDE.md",
    REPO_ROOT / "TECH_SPECS.md",
    REPO_ROOT / "CONTRIBUTING.md",
] + sorted((REPO_ROOT / "docs").rglob("*.md"))

R2_SKIP_DIRS = ("docs/history/", "docs/superpowers/")  # frozen archives + agent scratch

BACKTICK_RE = re.compile(r"`([^`\n]+)`")
PATHISH_RE = re.compile(
    r"^(?:\.claude|\.codex|\.github|libs|examples|tests|scripts|sql|cmake|docs|"
    r"build|CMakeLists\.txt|conanfile\.py|conan\.lock|"
    r"TECH_SPECS\.md|CHANGELOG\.md|README\.md)(?:[/\\]|$)"
)
PLACEHOLDER_RE = re.compile(
    r"<|>|\*|\{|N{2,}|xxx|XXX|YYYY|NNN|00N|\.\.\.|…|\$|:\d|\s"
)
# Runtime-provisioned secret locations (generated by operators, never tracked).
SECRET_EXTS = (".pem", ".key", ".crt", ".p12", ".pfx")

# Forward references: governance-phase deliverables that docs may cite
# before they land. Each entry needs a reason; prune as phases complete.
PENDING_PATHS: dict[str, str] = {
    # The coverage pipeline (measure_coverage.py + coverage.yml) landed, but
    # this file is written by the first green CI run, not by hand: seeding it
    # from a partial local run would pin fake floors.
    "scripts/coverage_baseline.json": "SEEDed by coverage.yml on its first green run",
}


def check_doc_paths() -> list[str]:
    errors: list[str] = []
    for doc in R2_DOCS:
        if not doc.is_file():
            continue
        rel_doc = doc.relative_to(REPO_ROOT).as_posix()
        if any(rel_doc.startswith(p) for p in R2_SKIP_DIRS):
            continue
        for lineno, line in enumerate(
            doc.read_text(encoding="utf-8", errors="replace").splitlines(), 1
        ):
            for token in BACKTICK_RE.findall(line):
                token = token.strip()
                if not PATHISH_RE.match(token) or PLACEHOLDER_RE.search(token):
                    continue
                token = token.rstrip(":").strip("/")
                probe = token.replace("\\", "/")
                if probe in PENDING_PATHS:
                    continue
                if probe.endswith(SECRET_EXTS):
                    continue
                if not (REPO_ROOT / probe).exists():
                    errors.append(
                        f"[rule2 dead-path] {rel_doc}:{lineno}: `{token}` does "
                        f"not exist (add to PENDING_PATHS with a reason if "
                        f"this is a deliberate forward reference)"
                    )
    return errors


# ---------------------------------------------------------------- R3

R3_BANNED = (
    "Google Test",
    "google test",
    "TEST_F(",
    "EXPECT_EQ(",
    "EXPECT_TRUE",
    "ASSERT_EQ",
    "gtest_filter",
    "gtest_verbose",
    "--gtest",
    "#include <gtest",
)
R3_ALLOW_LINE_RE = re.compile(r"not gtest|非 gtest|没有 gtest|gtest 宏不存在")
R3_ROOTS = [REPO_ROOT / "AGENTS.md", REPO_ROOT / "CLAUDE.md",
            REPO_ROOT / "TECH_SPECS.md", REPO_ROOT / "CONTRIBUTING.md"]
R3_DIRS = [REPO_ROOT / "docs", REPO_ROOT / ".claude", REPO_ROOT / ".codex"]
R3_SKIP_DIRS = ("docs/history/",)  # archives + CHANGELOG.md keep historical truth


def check_gtest_vocabulary() -> list[str]:
    errors: list[str] = []
    files: list[Path] = list(R3_ROOTS)
    for root in R3_DIRS:
        if not root.is_dir():
            continue
        files += [p for p in root.rglob("*")
                  if p.is_file() and p.suffix in {".md", ".toml", ".py", ".sh"}]
    for f in files:
        rel = f.relative_to(REPO_ROOT).as_posix()
        if any(rel.startswith(p) for p in R3_SKIP_DIRS):
            continue
        for lineno, line in enumerate(
            f.read_text(encoding="utf-8", errors="replace").splitlines(), 1
        ):
            if R3_ALLOW_LINE_RE.search(line):
                continue
            for token in R3_BANNED:
                if token in line:
                    errors.append(
                        f"[rule3 gtest-vocab] {rel}:{lineno}: '{token}' — "
                        f"this repo tests with Drogon DROGON_TEST"
                    )
                    break
    return errors


R4_SKIP_DIRS = ("docs/history/", "docs/superpowers/")
# READMEs that quote the chain by name, so they belong under the same rule as
# the governance docs even though they sit outside docs/.
R4_EXTRA_FILES = (
    REPO_ROOT / "README.md",
    REPO_ROOT / "examples" / "pay-server" / "README.md",
    REPO_ROOT / "libs" / "drogon-pay" / "src" / "models" / "README.md",
)

# `004_ledger_fk.sql` anywhere, with or without the sql/ prefix.
R4_FILE_RE = re.compile(r"(?<![\w/])(\d{3}_[a-z0-9][a-z0-9_]*\.sql)\b")
# `sql/004` without a filename.
R4_VERSION_RE = re.compile(r"sql/(\d{3})(?!\d)")
# "001 ~ 004" / "`000` → `001`" — backticks and separators between the numbers.
R4_RANGE_RE = re.compile(
    r"(?<!\d)(\d{3})[`\s]*(?:–|-|~|→|\.\.\.)[`\s]*(\d{3})(?!\d)"
)


def disk_migration_names() -> set[str]:
    return {p.name for p in (REPO_ROOT / "sql").glob("*.sql")}


def check_migration_versions() -> list[str]:
    """Rule 4 — docs may not cite a migration version the chain does not have.

    The migration chain is the one inventory that docs *and* skills quote by
    number, and a runbook that lists 001-004 while sql/ holds 001-006 is wrong
    in the way that gets copy-pasted into a deploy.
    """
    errors: list[str] = []
    names = disk_migration_names()
    versions = {name[:3] for name in names}
    files: list[Path] = list(R3_ROOTS) + [p for p in R4_EXTRA_FILES if p.is_file()]
    for root in R3_DIRS:
        if not root.is_dir():
            continue
        files += [p for p in root.rglob("*")
                  if p.is_file() and p.suffix in {".md", ".toml", ".py", ".sh"}]
    for f in files:
        rel = f.relative_to(REPO_ROOT).as_posix()
        if any(rel.startswith(p) for p in R4_SKIP_DIRS):
            continue
        for lineno, line in enumerate(
            f.read_text(encoding="utf-8", errors="replace").splitlines(), 1
        ):
            for name in R4_FILE_RE.findall(line):
                if name not in names:
                    errors.append(
                        f"[rule4 migration-cite] {rel}:{lineno}: cites "
                        f"{name}, which is not in sql/ (on disk: "
                        f"{', '.join(sorted(names))})"
                    )
            for version in R4_VERSION_RE.findall(line):
                if version not in versions:
                    errors.append(
                        f"[rule4 migration-cite] {rel}:{lineno}: cites "
                        f"sql/{version}, but no {version}_*.sql exists in sql/"
                    )
            if ".sql" in line or "sql/" in line:
                for low, high in R4_RANGE_RE.findall(line):
                    for value in range(int(low), int(high) + 1):
                        if f"{value:03d}" not in versions:
                            errors.append(
                                f"[rule4 migration-cite] {rel}:{lineno}: cites "
                                f"the range {low}-{high}, but {value:03d} is "
                                f"not in sql/ (head is "
                                f"{max(versions) if versions else '-'})"
                            )
    return errors


def main() -> int:
    violations = (check_asset_inventory() + check_doc_paths()
                  + check_gtest_vocabulary() + check_migration_versions())
    if violations:
        print(f"Docs drift guard FAILED ({len(violations)} violation(s)):")
        for v in violations:
            print("  " + v)
        return 1
    print("Docs drift guard passed (4 rules: inventory, dead-paths, "
          "gtest-vocab, migration-versions).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
